# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-11 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200211_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='up_name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
