# Generated by Django 3.0.2 on 2020-02-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HaloDjango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(db_column='name', max_length=20, unique=True)),
                ('s_age', models.IntegerField(db_column='age', default=0, unique=True)),
                ('s_happy', models.CharField(db_column='happy', max_length=40)),
            ],
            options={
                'db_table': 'happyDjango',
            },
        ),
    ]
