# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-03 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(db_column='classroom_name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(db_column='student_name', max_length=20)),
                ('s_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ForeignkeySearch.Classroom')),
            ],
        ),
    ]
