# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-26 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='axf_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField()),
                ('productimg', models.CharField(max_length=256)),
                ('productname', models.CharField(max_length=256)),
                ('productlongname', models.CharField(max_length=256)),
                ('isxf', models.BooleanField(default=True)),
                ('pmdesc', models.BooleanField(default=True)),
                ('specifics', models.CharField(max_length=128)),
                ('price', models.FloatField(default=1.0)),
                ('marketprice', models.FloatField(default=1.0)),
                ('categoryid', models.IntegerField(default=0)),
                ('childcid', models.IntegerField(default=0)),
                ('childcidname', models.CharField(max_length=128)),
                ('dealerid', models.IntegerField(default=0)),
                ('storenums', models.IntegerField(default=0)),
                ('productnum', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
