# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-26 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200226_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='axf_foodtypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(default=0)),
                ('typename', models.CharField(max_length=256)),
                ('childtypenames', models.CharField(max_length=256)),
                ('typesort', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'axf_foodtypes',
            },
        ),
    ]
