# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-27 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_axf_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axf_user',
            name='u_email',
            field=models.CharField(max_length=48, unique=True),
        ),
    ]
