# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-29 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200227_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopping_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_num', models.IntegerField(default=0)),
                ('s_isChoice', models.BooleanField(default=True)),
                ('s_isDelete', models.BooleanField(default=False)),
                ('s_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.axf_goods')),
                ('s_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.axf_user')),
            ],
            options={
                'db_table': 'axf_shopping_cart',
            },
        ),
    ]
