# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-29 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_shopping_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shopping_cart',
            new_name='axf_shopping_cart',
        ),
    ]
