# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-04 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200229_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='axf_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_time', models.DateTimeField(auto_now=True)),
                ('o_price', models.FloatField(default=0.0)),
                ('o_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.axf_user')),
            ],
            options={
                'db_table': 'axf_order',
            },
        ),
        migrations.CreateModel(
            name='axf_ordergoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('og_num', models.IntegerField(default=1)),
                ('og_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.axf_goods')),
                ('og_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.axf_order')),
            ],
            options={
                'db_table': 'axf_ordergoods',
            },
        ),
    ]
